### ISSUE TITLE
how do you install ?

### ISSUE THREAD

**Issue by adumont** [johnty/node-red-contrib-i2clcd#3]
How do you install this module in Node-Red?

**Comment by johnty** [comment]
updated README.MD with install instructions. let me know if you run into any issues!

**Comment by adumont** [comment]
Thanks, fixed with updated readme :) in 3a112067b4a670be16442e78f0ffd35e77614e55

**Comment by saeful1998** [comment]
hey i just installed and following your instruction in readme, but still have a lot error, for example
![image](https://user-images.githubusercontent.com/46883888/62490148-d250f380-b7f2-11e9-9dcf-fbc6df04747b.png)

**Comment by saeful1998** [comment]
is this work on node-red v 0.20.7 ?

**Comment by johnty** [comment]
According to the readme, IIRC the dependency i2c is no longer supported and needs to be manually compiled.

It should work with node v8.x; node-red version probably doesn’t matter unless it requires you to move up to node v10.x as well.

**Comment by saeful1998** [comment]
Sorry,but i dont know how to compile manuall and how fix that issues?

**Comment by johnty** [comment]
I made these instructions for someone a while ago, you can try and see if it works. note you need to have node v8.x instead of the latest for things to compile!

go to your node-red node_modules folder:

`cd ~/.node-red/node_modules`

Delete the old version (if it exists due to a previous automated install. if its not installed there then it won't find it):

`rm -rf node-red-contrib-i2clcd `

Clone the repo:

`git clone https://github.com/johnty/node-red-contrib-i2clcd`

now you should have the folder at

`~/.node-red/node_modules/node-red-contrib-i2clcd`

now go into the folder, and do an npm install:

```
cd node-red-contrib-i2clcd
npm i
```

this version should install fine with the correct dependency.

go back to your node-red home, and run node-red:

```
cd ~/.node-red
node-red
```
